### ISSUE TITLE
Blender S64 importing plugin

### ISSUE THREAD

**Issue by naclomi** [buu342/N64-Sausage64#26]
Hello! Firstly, thank you for the spectacular work on this modeling ecosystem :)

I was wondering if you had any plans to write a Blender plugin to _import_ S64 files?

I'm working on modding tools for the N64 release of Glover and the S64 format is perfectly suited to its actor data, but as-is I'm not sure if any modeling tools can read the format and it would be nice to have symmetry between the asset import and export workflows.

**Comment by buu342** [comment]
Hi, thanks for your interest in the project :smile:

I hadn't really considered it, especially because I've never messed with Blender's model import API. It can be done in the distant future, but definitely low priority for me.

**Comment by buu342** [comment]
Two years late on this, but I have basically begun work on an import plugin: [f7c7417](https://github.com/buu342/N64-Sausage64/commit/f7c7417923f50cc46352d29325d867d471d8c289)

Apologies for the silence, but I have been finishing my Masters degree, so I put all of my personal project stuff on hold until that was done. Now I'm tackling some Sausage64 stuff to get back into the swing of doing N64 related work, and this is something I'm currently working on.

The commit I made will read and parse the S64 file perfectly, now I just need to actually make it generate the meshes in Blender, and to animate them.

Now, since the S64 exporter doesn't export everything, the import process is somewhat lossy. One thing that isn't exported currently is bone parenting, because the library was designed to avoid the matrix stack in order to work around potential stack depth limitations. However, importing bones which aren't connected to one another is less than ideal for most people, so I'm going to have to modify the exporter to add a `PARENT` keyword to the mesh data in order for me to be able to connect bones. I won't be making long bones, however, I'll be doing something similar to what the Source Engine importer does where bones are made into spheres:
![image](https://github.com/buu342/N64-Sausage64/assets/9880691/04c5096b-fc6e-42a7-8b4f-8aa05ac5238c)

**Comment by naclomi** [comment]
Amazing! Welcome back :) . My modding tools are on hold themselves, but it's good to know this will be there when I get back to them!

**Comment by buu342** [comment]
Finished as of 9122abc, tested working in 2.7 and onwards. As explained, due to the S64 format, bone parenting information is lost, as well as texture data (meaning you have to re-assign the images to the materials). Everything else should work as expected (UVs, vertex colors, animations, etc...).
